version: '3.5'



services:
  db_auth:
    container_name: db_web
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: adctool
      POSTGRES_USER: Xiren
      POSTGRES_DB: db_main
      PGDATA: /Users/sasha/Desktop/albion/data
      POSTGRES_INITDB_ARGS: "-A md5"
    image: postgres:15.4-alpine3.18
    restart: always